### ISSUE TITLE
Deprecate this tap

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-gui#34]
We don't support it well and these are all things that better live in Homebrew Cask (and should have never been added to Homebrew/homebrew-core).

**Comment by midchildan** [comment]
Hi. I found out that most of these formulas can't be moved to Homebrew Cask, since they don't provide a binary release for macOS. They are also unlikely to be supported by Homebrew Cask in the future, since the Cask people explicitly say that they don't plan on supporting building apps from source in Caskroom/homebrew-cask#2245 . 

Here are the examples of formulas that doesn't have an upstream binary release for macOS:
- easytag
- gtk-chtheme
- geeqie
- gsmartcontrol
- hexchat
- iptux
- kernagic
- klavro
- smartsim
- tarsnap-gui
- terminator
- threadscope
- transmission-remote-gtk
- upnp-router-control
- xchat
- xournal

**Comment by MikeMcQuaid** [comment]
Thanks @midchildan. We'll need to think and talk about them. Some of them cannot really be packaged as a `.app` but some can so we may migrate some that can't and are very popular.

**Comment by MikeMcQuaid** [comment]
Handling this in https://github.com/Homebrew/homebrew-gui/issues/52. Migrated some to Homebrew Cask and the rest (that weren't removed for popularity reasons) to homebrew/core.
